<?php

/**
 * Implements hook_access_certificate().
 */
function signup_certificate_access_certificate($node, $user) {
  if (in_array($node->type, signup_content_types())) {
    $sql = "SELECT 1 FROM {signup_log} WHERE nid = :nid AND uid = :uid AND attended = 1";
    // TODO: Drupal Rector Notice: Please delete the following comment after you've made any necessary changes.
    // You will need to use `\Drupal\core\Database\Database::getConnection()` if you do not yet have access to the container here.
    $attended = \Drupal::database()->query($sql, array(':nid' => $node->nid, ':uid' => $user->uid))->fetchField();
    return (bool) $attended;
  }
}
