_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bpmn_io: 0
  breakpoint: 0
  certificate: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_cache: 0
  eca_config: 0
  eca_content: 0
  eca_endpoint: 0
  eca_form: 0
  eca_log: 0
  eca_migrate: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_render: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  editor: 0
  entity: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flexible_permissions: 0
  gin_toolbar: 0
  gnode: 0
  group: 0
  group_support_revisions: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  masquerade: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  migrate: 0
  mysql: 0
  node: 0
  node_token: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pdf_api: 0
  printable: 0
  printable_pdf: 0
  rules: 0
  scheduler: 0
  scheduler_rules_integration: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  typed_data: 0
  update: 0
  user: 0
  variationcache: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_devel: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  workflows: 0
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
profile: standard
