_core:
  default_config_hash: kKv7Dnslf8BJx3FRlURT0bIwEs3nJ3DkcNuSLTbvVVE
printable_entities:
  - node
  - comment
  - user
open_target_blank: true
css_include: ''
extract_links: none
save_pdf: false
pdf_tool: ''
paper_size: A4
page_orientation: Portrait
path_to_binary: ''
pdf_location: ''
send_to_printer: false
close_window: false
list_attribute: false
printable_print_link_locations:
  - node
printable_pdf_link_locations:
  - ''
print_pdf_use_xvfb_run: false
path_to_xvfb_run: ''
ignore_warnings: false
